branches:
    only:
        - master
sudo: required
language: php
php:
    - '5.6'
    - '7.1'
    - '7.3'
    - '7.4'
services:
    - mysql
install:
    - composer install
script: 
    - wget -O phpunit.phar https://phar.phpunit.de/phpunit-5.phar
    - php phpunit.phar -c tests/phpunit.xml --bootstrap tests/bootstrap_autoload_mysql.php tests
    - php phpunit.phar -c tests/phpunit.xml --bootstrap tests/bootstrap_autoload.php tests
    - composer remove aphp/foundation
    - composer require aphp/foundation ~1.0.0
    - php phpunit.phar -c tests/phpunit.xml --bootstrap tests/bootstrap_autoload.php tests
notifications:
    email: false