branches:
    only:
        - master
sudo: required
language: php
php:
    - '5.6'
services:
    - mysql
install:
    - composer install
script: 
    - wget -O phpunit.phar https://phar.phpunit.de/phpunit-5.phar
    - php phpunit.phar -c tests/phpunit.xml --bootstrap tests/bootstrap_autoload_mysql.php tests
notifications:
    email: false